name: Python Tests

on:
  push:
    branches: [ master, develop, feature/**, bugfix/**, hotfix/** ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Start database service
      run: |
        docker compose up -d db
        sleep 10
    
    - name: Start API service
      run: docker compose up -d api
      
    - name: Wait for API to start
      run: sleep 5
      
    - name: Run tests
      run: |
        docker compose exec -T api pytest -v
    
    - name: Tear down services
      run: docker compose down -v
      if: always()
